version = 1

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "php"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Sheik-md/Broken-Vulnerable-Code-Snippets"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "javascript"